### ISSUE TITLE
Command is not working

### ISSUE THREAD

**Issue by marcospc20** [riquenunes/pegasus-theme-npe#1]
Commands are not working, I can't move left or right or change the game, no command works.
any tips, because I saw that in the video it works perfectly. I followed installation instructions but when adding the theme the commands do not work

**Comment by riquenunes** [comment]
That's weird. What platform are you running on? Do other themes work normally? Can you select between collections at least? (up, down)

**Comment by marcospc20** [comment]
I made a video for you to understand better what happens I can move up and down normally I just can't move left and right on the covers screen if I press the button X games details I can go right and left more on the main screen of the game covers I can't go to the side only up and down
https://www.youtube.com/watch?v=LCbCMWBzXyQ

**Comment by riquenunes** [comment]
Nice, the video is super helpful, thank you. It's interesting how it works on the details page and not on the games library, as the same component is shared between them. I'll try to figure this out

**Comment by marcospc20** [comment]
Hi Henrique I'm waiting for the correction of the theme this theme is very beautiful I feel like I'm on my own xbox 360 I'm waiting for the Xbox 360 Kinect Dashboard it must be even better

**Comment by riquenunes** [comment]
Glad to hear it @marcospc20! I expect the Kinect one to be even better, as, funnily enough, the NXE dashboard had even more complex UI elements that I wasn't able to get 100% right.

Anyways, can you test this version and see if it fixes the navigation issue? https://github.com/riquenunes/pegasus-theme-npe/archive/refs/heads/navigation-issue-test.zip

**Comment by marcospc20** [comment]
Hello Henrique, I took the test, it continues the same way, nothing has changed, I continue without navigation.
how is a small file can you send me your pegasus folder already with the theme for me to see if it works?

**Comment by riquenunes** [comment]
> Hello Henrique, I took the test, it continues the same way, nothing has changed, I continue without navigation

Can you try that again? https://github.com/riquenunes/pegasus-theme-npe/archive/refs/heads/navigation-issue-test.zip
I've made another change to what I suspect that may be the issue

> How is a small file can you send me your pegasus folder already with the theme for me to see if it works?

Well, my Pegasus folder doesn't have anything special really, all the games I showed are from Steam or Playnite, so I don't really have any metadata files in there. I suspected there could be a version difference as well, but we seem to be running on the same version (2022-10-14).

Maybe for some reason it doesn't work properly with the metadata.txt files? If the problem persists could you maybe send your metadata so I can try replicating the issue here?

**Comment by marcospc20** [comment]
Hi Henrique, now it's working perfectly!!! Thanks for the help, I'll send you a video showing how it works later :)

**Comment by denisidoro** [comment]
Hi! I was experiencing the same issue and I confirm that the fix above did the trick.

Once it gets to the master branch, I guess we can close this ticket. 👍

**Comment by riquenunes** [comment]
Glad to know it fixed it! I pushed these changes to master and am closing this issue now. Thanks for the feedback!

**Comment by marcospc20** [comment]
Thank you Henrique for the Theme I look forward to news about Xbox 360 Kinect Dashboard and the future Xbox Series
